// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlYaoYLg-9WFTGzhmEEWBNpbCGFbyh3CY',
    appId: '1:649433381531:web:df5d55a80ab2db0a76e43e',
    messagingSenderId: '649433381531',
    projectId: 'buildsafespace',
    authDomain: 'buildsafespace.firebaseapp.com',
    storageBucket: 'buildsafespace.firebasestorage.app',
    measurementId: 'G-V5JQSVMYVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVdT30TCtL8QwAVMlPwHuFaYkHG9P77a4',
    appId: '1:649433381531:android:54dd6e40f17326cc76e43e',
    messagingSenderId: '649433381531',
    projectId: 'buildsafespace',
    storageBucket: 'buildsafespace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLh5lUZuqJc2fF4Baaa6DgnoDmScPH2K4',
    appId: '1:649433381531:ios:e2b708df6dca2aea76e43e',
    messagingSenderId: '649433381531',
    projectId: 'buildsafespace',
    storageBucket: 'buildsafespace.firebasestorage.app',
    iosBundleId: 'com.example.safeSpace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLh5lUZuqJc2fF4Baaa6DgnoDmScPH2K4',
    appId: '1:649433381531:ios:e2b708df6dca2aea76e43e',
    messagingSenderId: '649433381531',
    projectId: 'buildsafespace',
    storageBucket: 'buildsafespace.firebasestorage.app',
    iosBundleId: 'com.example.safeSpace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlYaoYLg-9WFTGzhmEEWBNpbCGFbyh3CY',
    appId: '1:649433381531:web:4e182455262ebc1376e43e',
    messagingSenderId: '649433381531',
    projectId: 'buildsafespace',
    authDomain: 'buildsafespace.firebaseapp.com',
    storageBucket: 'buildsafespace.firebasestorage.app',
    measurementId: 'G-N6X4EE8RY4',
  );

}